version: '3'
services:
    db:
        container_name: flyerdb
        image: mvertes/alpine-mongo 
    app:
        container_name: manger
        build: .
        environment:
            - DB_CONNECTION=mongodb://flyerdb:27017
        depends_on:
            - "db"
    web:
        build: auth_proxy
        ports:
            - 80:80
        depends_on:
            - "app"
